#!/usr/bin/env bash

set -eu

cd "$WD/build"
cp "$WD/src/main.ml" ./
ocamlfind \
    ocamlc \
    -w +1..66 \
    -thread \
    -package Lwt,Lwt.unix \
    -linkpkg main.ml \
    -o "$WD/bin/concaml"

cd "$WD"
./bin/concaml
